/**
 * @file 2.c
 * @author Dev Sanghvi (Dev04san@gmail.com)
 * @brief Even Fibonacci numbers
 * @version 1.0
 * @date 2023-03-04
 *
 * @copyright Copyright (c) 2023
 *
 */

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>

int main() {
    long long limit = 4000000;
    long long maxEvenFib = 2;
    long long a = 1, b = 2, c = 3, sum = 2;
    while (c <= limit) {
        if (c % 2 == 0) {
            sum += c;
            maxEvenFib = c;
        }
        a = b;
        b = c;
        c = a + b;
    }
    long long n = (maxEvenFib / 3) + 1;
    double phi = (1 + sqrt(5)) / 2;
    double psi = (1 - sqrt(5)) / 2;
    double f = (pow(phi, n) - pow(psi, n)) / sqrt(5);
    long long evenSum = (long long)((f - 1) / 2);
    printf("%lld\n", evenSum);
    return 0;
}