name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: [windows-latest,macos-13,ubuntu-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: Dv04/Coded@main
